# Name of the reference PGLib case. Must be a valid PGLib case name.
ref = "pglib_opf_case1354_pegase"
# Directory where instance/solution files are exported
# must be a valid directory
export_dir = "data/1354_mu0001"

[sampler]
# ACOPF sampler options
[sampler.load]
noise_type = "ScaledLogNormal"  # Only "ScaledLogNormal" is supported at the moment
l          = 0.8                # Lower bound of base load factor
u          = 1.25               # Upper bound of base load factor
sigma      = 0.15               # Relative (multiplicative) noise level.

[OPF]

[OPF.DCPPowerModel]
    type = "DCPPowerModel"
    [OPF.DCPPowerModel.solver]
        name = "Mosek"

[OPF.StandardFormDCPPowerModel_mu01]
    type = "StandardFormDCPPowerModel"
    [OPF.StandardFormDCPPowerModel_mu01.solver]
        name = "Mosek"
        [OPF.StandardFormDCPPowerModel_mu01.solver.attributes]
    [OPF.StandardFormDCPPowerModel_mu01.kwargs]
        objective_kind = "conic"
        mu = 0.1
