# Name of the reference PGLib case. Must be a valid PGLib case name.
ref = "pglib_opf_case1354_pegase"
# Directory where instance/solution files are exported
# must be a valid directory
export_dir = "data/1354_mu0001"

standard_form_objective_type = 'cone' # linear, cone
standard_form_mu = 0.0001

[sampler]
# ACOPF sampler options
[sampler.load]
noise_type = "ScaledLogNormal"  # Only "ScaledLogNormal" is supported at the moment
l          = 0.8                # Lower bound of base load factor
u          = 1.25               # Upper bound of base load factor
sigma      = 0.15               # Relative (multiplicative) noise level.

[OPF]
StandardFormDCPPowerModel = "Mosek"
DCPPowerModel = "Mosek"

[solver]
[solver.Mosek]