# Name of the reference PGLib case. Must be a valid PGLib case name.
pglib_case = "89_pegase"
# Directory where instance/solution files are exported
# must be a valid directory
export_dir = "data/89_pegase"

[sampler]
# Sampler options
[sampler.load]
noise_type = "ScaledUniform"
l          = 0.60               # Lower bound of base load factor
u          = 1.00               # Upper bound of base load factor
sigma      = 0.15               # Relative (multiplicative) noise level.

[sampler.reserve]
type   = "E2ELR"
l      = 1.0
u      = 2.0
factor = 5.0

[sampler.status]
type = "Full"


[OPF]
# OPF formulations to solve for each sample
[OPF.DCOPF]
# Formulation/solver options
type = "DCOPF"
solver.name = "HiGHS"

[OPF.ACOPF]
type = "ACOPF"
solver.name = "Ipopt"
solver.attributes.tol = 1e-6
solver.attributes.linear_solver = "ma27"

[OPF.EDSoftThermal]
type = "EconomicDispatch"
kwargs.soft_thermal_limit = true
solver.name = "HiGHS"

[OPF.SOCOPF]
type = "SOCOPF"
solver.name = "Clarabel"
# Tight tolerances
solver.attributes.tol_gap_abs    = 1e-6
solver.attributes.tol_gap_rel    = 1e-6
solver.attributes.tol_feas       = 1e-6
solver.attributes.tol_infeas_rel = 1e-6
solver.attributes.tol_ktratio    = 1e-6
# Reduced accuracy settings
solver.attributes.reduced_tol_gap_abs    = 1e-6
solver.attributes.reduced_tol_gap_rel    = 1e-6
solver.attributes.reduced_tol_feas       = 1e-6
solver.attributes.reduced_tol_infeas_abs = 1e-6
solver.attributes.reduced_tol_infeas_rel = 1e-6
solver.attributes.reduced_tol_ktratio    = 1e-6

[OPF.SOCOPF128]
# These settings are meant to solve `SOCWRConic` problems to high precision
type = "SOCOPF"
solver.name = "Clarabel128"
solver.attributes.max_iter = 2000
solver.attributes.max_step_fraction = 0.995
# Disabling scaling can avoid violations (especially in the dual)
# /!\ This results in worse performance /!\
solver.attributes.equilibrate_enable = true
# Tight tolerances
solver.attributes.tol_gap_abs    = 1e-12
solver.attributes.tol_gap_rel    = 1e-12
solver.attributes.tol_feas       = 1e-12
solver.attributes.tol_infeas_rel = 1e-12
solver.attributes.tol_ktratio    = 1e-10
# Reduced accuracy settings
solver.attributes.reduced_tol_gap_abs    = 1e-8
solver.attributes.reduced_tol_gap_rel    = 1e-8
solver.attributes.reduced_tol_feas       = 1e-8
solver.attributes.reduced_tol_infeas_abs = 1e-8
solver.attributes.reduced_tol_infeas_rel = 1e-8
solver.attributes.reduced_tol_ktratio    = 1e-7
# Additional linear solver-related settings, to match precision of Float128
solver.attributes.static_regularization_enable = false  # typically not needed unless tolerances go below 1e-14
solver.attributes.dynamic_regularization_enable = true  # kept for safety
solver.attributes.dynamic_regularization_eps = 1e-28
solver.attributes.dynamic_regularization_delta = 1e-14
solver.attributes.iterative_refinement_reltol = 1e-18
solver.attributes.iterative_refinement_abstol = 1e-18

[slurm]
# SLURM options
n_samples = 65536
n_jobs = 45
queue = "embers"
charge_account = "gts-phentenryck3-ai4opt"
