# Name of the reference PGLib case. Must be a valid PGLib case name.
ref = "pglib_opf_case300_ieee"
# Directory where instance/solution files are exported
# must be a valid directory
export_dir = "data/300_ieee"

[sampler]
# Sampler options
[sampler.load]
noise_type = "ScaledLogNormal"  # Only "ScaledLogNormal" is supported at the moment
l          = 0.8                # Lower bound of base load factor
u          = 1.20               # Upper bound of base load factor
sigma      = 0.15               # Relative (multiplicative) noise level.


[OPF]
# OPF formulations to solve for each sample
[OPF.DCOPF]
# Formulation/solver options
type = "DCPPowerModel"
solver.name = "Mosek"

[OPF.ACOPF]
type = "ACPPowerModel"
solver.name = "Ipopt"
solver.attributes.tol = 1e-5
solver.attributes.linear_solver = "ma27"


[slurm]
# SLURM options
n_samples = 65536
n_jobs = 45
queue = "embers"
charge_account = "gts-phentenryck3-ai4opt"