# Name of the reference PGLib case. Must be a valid PGLib case name.
ref = "pglib_opf_case300_ieee"
# Directory where instance/solution files are exported
# must be a valid directory
export_dir = "data/ieee300"

[sampler]
# ACOPF sampler options
[sampler.load]
noise_type = "ScaledLogNormal"  # Only "ScaledLogNormal" is supported at the moment
l          = 0.8                # Lower bound of base load factor
u          = 1.05               # Upper bound of base load factor
sigma      = 0.05               # Relative (multiplicative) noise level.

[OPF]
ACPPowerModel = "Ipopt"
DCPPowerModel = "Mosek"
SOCWRConicPowerModel = "Mosek"

[solver]

[solver.Ipopt]
tol = 1e-6
print_level = 0
max_wall_time = 60.0
linear_solver = "ma27"

[solver.Mosek]
MSK_IPAR_NUM_THREADS = 1
MSK_DPAR_OPTIMIZER_MAX_TIME = 60.0