# Name of the reference PGLib case. Must be a valid PGLib case name.
ref = "pglib_opf_case300_ieee"
# Directory where instance/solution files are exported
# must be a valid directory
export_dir = "data/ieee300"

[sampler]
# ACOPF sampler options
[sampler.load]
noise_type = "ScaledLogNormal"  # Only "ScaledLogNormal" is supported at the moment
l          = 0.8                # Lower bound of base load factor
u          = 1.05               # Upper bound of base load factor
sigma      = 0.05               # Relative (multiplicative) noise level.

[solver]
# Optimization solver options
name = "Ipopt"                  # only "Ipopt" is supported at the moment
tol = 1e-6                      # numerical tolerance (leave it at 1e-6 unless you know what you're doing)
print_level = 0                 # set this to zero to disable Ipopt output
max_wall_time = 60.0            # time limit, in seconds
